title : Aplicación de Escritorio para manejo de planillas Excel con Javax
description: Creado por Laureano Blonsky, Mentor de Programá tu Futuro, Sede Usuaria
author :
  name : Laureano Blonsky
  email : laureano.blonsky@bue.edu.ar
  github : https://github.com/LaureanoBlonsky
theme: jekyll-theme-cayman
